# Generated by Django 5.1 on 2024-08-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomoderatedbooksmodel",
            name="user",
            field=models.CharField(
                max_length=80, null=True, verbose_name="Введите свой никнэйм"
            ),
        ),
    ]
