# Generated by Django 5.1 on 2024-08-20 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("bio", models.TextField()),
            ],
            options={
                "verbose_name": "Автор",
                "verbose_name_plural": "Авторы",
            },
        ),
        migrations.CreateModel(
            name="EBooksModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Название")),
                (
                    "summary",
                    models.TextField(max_length=10000, verbose_name="Аннотация"),
                ),
                (
                    "pages",
                    models.CharField(max_length=80, verbose_name="Количество страниц"),
                ),
                (
                    "txt",
                    models.FileField(
                        upload_to="texts/txt/",
                        verbose_name="Загрузите файл в формате txt",
                    ),
                ),
                (
                    "fb2",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="texts/fb2/",
                        verbose_name="Загрузите файл в формате fb2",
                    ),
                ),
                (
                    "epub",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="texts/epub/",
                        verbose_name="Загрузите файл в формате epub",
                    ),
                ),
                ("category", models.CharField(max_length=80, verbose_name="Категория")),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangolib.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Электронная книга",
                "verbose_name_plural": "Электронные книги",
            },
        ),
        migrations.CreateModel(
            name="FavouriteBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_on", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangolib.ebooksmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
